### ISSUE TITLE
Journal link in README.md does not work

### ISSUE THREAD

**Issue by sdroege** [eellak/gsoc2018-cantarell#2]
First of all, thanks for working on this. This is something that is making me sad when using GNOME since I started learning Greek. Having proper support for it in Cantarell is going to be a big improvement for me and many other people :)
The results so far in your test PDF also look very promising, good work!

There's also an issue about this in the GNOME GitLab here: https://gitlab.gnome.org/GNOME/cantarell-fonts/issues/1

Now to the only problem, the link to your journal in the README.md does not work :) It is https://github.com/eellak/gsoc2018-cantarell/blob/master/00_PROCESS/Journal.md but should be https://github.com/eellak/gsoc2018-cantarell/blob/master/00_PROCESS/JOURNAL.md (uppercase)

**Comment by thynem** [comment]
Hello @sdroege 
Thank you for your comments. 
Link is now corrected. 
-- cc @grautesk

**Comment by grautesk** [comment]
Thank you @sdroege for pointing me to the issue. It’s nice to know that what I’m working on is anticipated and actually going to be used.

**Comment by madig** [comment]
Absolutely. Cantarell has been thrown off the newest Fedora release for not
having the same language coverage as the old design.
